Makefile
In the `go build` command, replace `github.com/Cepave/open-falcon` with `.`.
=> [OWL-370] Replace absolute path with relative path

modules/fe/http/dashboard/dashboard_controller.go, modules/fe/http/dashboard/dashboard_routes.go, modules/fe/model/dashboard/models.go, modules/fe/mq/mq.go, modules/fe/views/dashboard/endpoints.html
Original plugin state summary page has only git commit hash. 
In this patch, column date and title are added into this page. Therefore, this page has more git information.
=> [OWL-509][fe] improve plugin state summary page

common/vipercfg/vipercfg.go
Substituting `SetConfigFile()` for `SetConfigName()` solved the problem of getting wrong configuration file path.
=> [OWL-253][common] Fix the path problem

modules/nqm-agent/calc.go, modules/nqm-agent/calc_test.go
Now `nqm-agent` considers the packets of transmission time more than 1000ms as lost packets.
=> [OWL-709][nqm-agent] Count `rtt` more than 1s lost

modules/query/http/zabbix.go
Originall, there are 68 lines of log.Println in file **http/zabbix.go**.
split the log level and change the logs to log.Debugln, log.Errorln, and log.Println.
=> [OWL-744][query] split the log level in zabbix query

modules/fe/http/dashboard/dashboard_controller.go, modules/fe/http/dashboard/dashboard_routes.go
The new API ```endpointrunningplugins``` will probe agent's current running plugins. This API can help to debug when we want to fully be sure that certain plugins are running on some hosts or not.
=> [OWL-791][fe] add new API to support probing running plugins

modules/fe/http/dashboard/dashboard_controller.go, modules/fe/http/dashboard/dashboard_routes.go, modules/fe/model/dashboard/endpoint_counter.go
[OWL-627][fe] API for query endpoints by counter
provide new API api/v1/dashboard/counterendpoints which has two mode to use it. 
1. use the parameter **counter**.
In this mode, this API can retrieve all the endpoints that have certain counter. 
2. use the parameter **metricQuery**, with **negateMatch**=true or false.
In this mode, this API can retrieve all the endpoint match or not match certain counter pattern.
=> [OWL-627][fe] API for query endpoints by counter

modules/fe/cfg.example.json, modules/fe/g/cfg.go, modules/fe/http/dashboard/dashboard_controller.go
Move the hardcoded address to config file. 
`https://gitlab.com/Cepave/OwlPlugin/commits/master.atom` will now be stored in variable `g.Config().AtomAddr`
=> [OWL-890][fe] move the hardcoded address to config

common/model/agent.go, modules/agent/cron/plugin.go, modules/agent/cron/reporter.go, modules/agent/g/cfg.go, modules/agent/g/tool.go, modules/agent/http/plugin.go, modules/agent/plugins/plugins.go, modules/hbs/cache/cache.go, modules/hbs/cache/gitupdate.go, modules/hbs/cfg.example.json, modules/hbs/g/cfg.go, modules/hbs/rpc/agent.go
1. RPC Agent.ReportStatus  會對 HBS 送出
1. git 最新的 commit hash 
2. agent 目前使用的git repo 
2. HBS 會定期去詢問 `plugin git repo address` ，去抓取最新的 `git commit hash`
3. 當 HBS 送給 Agent 的資料，含有 `GitUpdate = true` 時，Agent 會去更新 `plugin` 的版本。
4. 當 HBS 送給 Agent 的資料，含有 `GitRepoUpdate = true` 時，Agent 會去更新 `plugin git repo address`
=> [OWL-867][agent][hbs][common] HBS policy includes git update and git repo update info 

modules/agent/cfg.example.json, modules/agent/funcs/checker.go, modules/agent/funcs/ifstat.go, modules/agent/funcs/ifstat_test.go, modules/agent/g/cfg.go
Originally, **iface=eth_all** only collects **eth, em, enp**  iface interfaces. 
In this modification, **iface=eth_all** will collect all the interfaces that assigned in the **collector.eth_all**  in config file. 
For example, in below cases, 
```
"collector": {
"ifacePrefix": ["eth", "em", "bond", "enp", "p2p2"] ,
"eth_all": ["eth", "em", "enp", "p2p2"]
},
```
**iface=eth_all**  will collect **eth, em, enp, p2p2**  interfaces .
=> [OWL-637][agent] change iface prefix matching code segment

modules/agent/cron/plugin.go
當 agent 從 HBS 收到哪些的 dir 要視為「現在要執行的 plugin dir 」時，對這些 dir 做過濾(filtering)。去除下列兩種字串
1.  ”data”
2.  含有 "data/" prefix
=> [OWL-897][agent] reserve data dir under plugin dir.

common/model/agent.go, modules/hbs/rpc/agent.go
OWL-867 modify HBS and Agent modules at the same time. Considering DevOps issues, new HBS will be first updated, then we updated all the 5000 Agents. To make sure that new version of HBS can cooperate with old version of Agent. We add some more Debug log into HBS and common.
=> [OWL-867][hbs][common] add necessary debug message for verification

modules/agent/control, modules/agent/cron/reporter.go, modules/agent/g/tool.go
Agent automatically updating plugin directory halts because of RPC **Agent.ReportStatus** fail.
Open-falcon original GetCurrPluginVersion() is somewhat badly written. Refactor it in this commit.
=> [OWL-693][OWL-964][agent] Hotfix of bug: agent automatically updating plugin dir will halt

modules/agent/http/plugin.go, modules/agent/http/plugin_test.go
1 add a function  RunCmdWithTimeout to prevent "git clone" and "git pull" block the go routine. 
2 add a unit test to test RunCmdWithTimeout.
=> [OWL-975][agent] add command timout to prevent goroutine blocking

modules/agent/http/plugin.go, modules/agent/http/plugin_test.go
Fix two primary problems: 
1. goroutine leak problem
2. log.fatal problem
Originally in OWL-975, the previous version of `func RunCmdWithTimeout` suffers from goroutine leaking problem when timeout happens. Use the `sys.CmdRunWithTimeout` provided by open-falcon author instead. 
Ref:
https://github.com/golang/go/wiki/Timeouts
In Golang, log.fatal will call os.exit(1) after print out error messages. This kind of log behavior is out of my expectation. 
http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#log_fatal_exit
=> [OWL-975][agent] fix go routines leak problem and log.fatal problem.

common/pool/pool.go, modules/agent/g/rpc.go, modules/nqm-agent/rpc.go, modules/transfer/sender/conn_pool/conn_pool_manager.go, modules/transfer/sender/conn_pool/influxdb_conn_pool_manager.go, modules/transfer/sender/conn_pool/nqmrpc_conn_pool_manager.go, modules/transfer/sender/conn_pool/staging_conn_pool_manager.go
fix goroutine leaks problem when timeout really happens.
Ref https://github.com/golang/go/wiki/Timeouts  
Using channel to implement timeout, channel should have a buffer size of one. Otherwise, the goroutine that has the send channel would never be destroyed when timeout really happens.
=> [OWL-1011][agent][common][transfer][nqm-agent] fix goroutine leaks.

modules/transfer/http/proc_http.go
Originally, transfer generates panic log when API `trace` is used in the wrong way. 
Now it sends out proper message to remind user the API `trace` is not properly used.
=> [OWL-989][transfer] fix transfer panic when API trace is used in the wrong way. 

modules/transfer/http/common.go, modules/transfer/http/proc_http.go
原始的 transfer API `config/reload` 就沒有考慮許多複雜的情況。
現在因為在某些情況，會發生 panic ，先將這個 API 關閉。
目前可以用 restart 做為替代方案
=> [OWL-988][transfer] 關閉 transfer 的 config/reload API

modules/agent/cron/builtin.go, modules/agent/cron/builtin_test.go
`proc.num` with no tags -> record all the process number
`proc.num` with only name tag -> record the process number of process name
`proc.num` with only cmdline tag -> record  the process number of process cmdline
Otherwise, do not record any data.
=> [OWL-700][agent] fix builtin metric proc.num on special cases

modules/fe/Portal_APIDoc.md, modules/fe/http/portal/onTimeUpdate_controller.go, modules/fe/http/portal/portal_controller.go, modules/fe/model/falcon_portal/alerts.go, modules/fe/model/falcon_portal/event_query_action.go
1. currently the latest alarms page of owl-light is not required, set this by optional response data set to improve response time.
2. fix a logic error of EventNotes api, but current no any front-end use this api, no this not affect ours owl-light, this error is found by my test script.
3. move getNotes action after boss api filter action, this can reduce sql computing time
=> [OWL-1008] [fe] Improve alerts reponse time, by set events info as optional data set

modules/alarm/http/http.go, modules/fe/http/http.go
Set default beego logger to monochrome output.
There are still color codes with debug(DEV) mode due to the lack of option in beego.
=> [OWL-1016][alarm][fe] Set default beego logger to monochrome output.

modules/agent/http/plugin.go, modules/agent/http/plugin_test.go, modules/agent/plugins/scheduler.go
```
err = cmd.Start()
err, isTimeout = sys.CmdRunWithTimeout(...)
```
In this commit, `err` is properly handled so as to let exception to be discovered easily.
=> [OWL-1025][agent] add detailed error msg on sys.CmdRunWithTimeout

modules/agent/funcs/agent.go, modules/agent/funcs/funcs.go, modules/nodata/collector/collector_cron.go, modules/nodata/judge/judge_cron.go
1. In order to make the `agent.alive` builtin metric more sensible, especially add a new builtin metric `agent.alive.30sec`.  This builtin metric `agent.alive.30sec` can be used with `nodata` to detect whether `agent` is alive. 
2. In `nodata`, the collect, judge, send cycle has been changed to minimum 30 seconds so as to collaborate with `agent.alive.30sec`
3. In `nodata`, the minimum timeout changes from 180 seconds to 90 seconds. 
1. Setup a template rule to detect `agent.alive.30sec`. For example, `all(#6) < 1`
2. Setup `nodata` to trace `agent.alive.30sec`. For example, ` metric: agent.alive.30sec, type: GAUGE, step: 30, value: -1`
=> [OWL-937][agent] Add a new builtin metric "agent.alive.30sec"

Makefile
`Makefile` still got the version number from `g/version.go`, which should be replaced with `VERSION` in the root of the working directory.
=> [OWL-998][backend] Fix `make pack`

Makefile
In the original `Makefile`, the `make all` failed due to the incorrect code. Also, the `rm -rf ./vendor` wasn't added in `make clean`.
=> [OWL-1018][backend] Fix `all`, `trash` & `clean`

main.go
Now the flags of `--console-output` & `--preq-order` of `start` command works properly.
=> [OWL-998][backend] Fix the flags of subcommands

Makefile, configure
In this PR, the I move `trash` from `Makefile` to `configure`, which runs `go get ./...` too
=> [OWL-1018][backend] Use `configure` for setting the building environment

modules/nqm-agent/task_test.go, modules/transfer/sender/sender.go, modules/transfer/sender/sender_test.go
This PR is a temporary workaround, which only allows the metric of `nqm-fping` to be sent to Cassandra DB. Before `nqm-tcpping` and `nqm-tcpconn` is supported, it should work this way.
=> [OWL-900][transfer] Specify `nqm-fping` exactly

modules/nqm-agent/query.go, modules/nqm-agent/rpc.go, modules/nqm-agent/task_test.go, modules/nqm-agent/version.go, modules/transfer/sender/sender.go, modules/transfer/sender/sender_test.go
In this PR, I changed how `RPCCall` works. Previously `nqm-agent` establishes a connection to `hbs` as a global variable and it checks if this variable is valid before every single RPC call. I changed this mechanism. Now it sets up a connection before a call and tears it down after that.
=> [OWL-1103][nqm-agent] Fix the problem that `nqm-agent` crashes after restarting `hbs` 

modules/nqm-agent/cfg.go, modules/nqm-agent/main.go, modules/nqm-agent/marshal.go, modules/nqm-agent/push.go, modules/nqm-agent/query.go, modules/nqm-agent/rpc.go, modules/nqm-agent/task.go
In this PR, the unmarshalling is done by `viper`, not by the `encode/json`. Some unnecessary functions are removed due to this change. I also refined some code.
=> [OWL-677][nqm-agent] Redesign the mechanism of initialization

modules/query/http/cron.go, modules/query/http/grafana_graph_options.go
The data in `hosts` table of `boss` database is not synchronized with BOSS API precisely.
This error is due to beego ORM module has default `limit` number and some dirty variables.
This is a temporary quick solution. More suitable solution should proper use SQL syntax like transactions, temp table to replace great quantity of data transferring between memory and database.
=> [OWL-1199][query] fix cronjob of hosts from BOSS API inside query module 

modules/query/http/cron.go, modules/query/http/grafana_graph_options.go
The data in `hosts` table of `boss` database is not synchronized with BOSS API precisely. 
This error is due to beego ORM module has default `limit` number and some dirty variables. 
This is a temporary quick solution. More suitable solution should proper use SQL syntax like transactions, temp table to replace great quantity of data transferring between memory and database.
=> [OWL-1199][query] fix cronjob of hosts from BOSS API  inside query module

modules/agent/http/plugin.go, modules/agent/http/plugin_test.go
`sys.CmdRunWithTimeout` cannot kill all the children processes.
Replace it with `cmdSessionRunWithTimeout`
=> [OWL-1256][agent] fix 'git orphan processes' bug

Makefile
f5d27fb was a mistake. In our `docker` environment, we still need `trash` in `Makefile` because we are not using `configure`.
=> [OWL-1018][backend] Add `trash` back to `Makefile`

modules/nqm-agent/cfg.go
In this commit, it removes the dependency `dig` and it uses the package `pubip` which sends HTTP requests to several APIs for getting a valid public IP address. Take a look at [pubip](https://github.com/chyeh/pubip) for more details.
=> [OWL-1335][nqm-agent] A new way to get public IP

scripts/mysql/db_schema/boss-db-schema.sql, scripts/mysql/dbpatch/change-log/change-log-boss.yaml, scripts/mysql/dbpatch/change-log/schema-boss/laurence-4.sql
Boss API 新增了 `ip_type` 的欄位。要做虛擬 ip 的監控，就必須在 `boss.hosts` 增加對應的欄位 `type`。其它的欄位根據 don 的需求新增。已經用 db_patch 和 mysqldiff 做過驗証。
=> [OWL-1243][scripts] modify db schema in boss database

modules/transfer/sender/queue_item.go
The Cassandra API has supported `group_tag_ids`, so the previous workaround can be removed now.
=> [OWL-865][transfer] Support `GroupTagIds`

scripts/mysql/db_schema/grafana_database-db-schema.sql
In order to change the default database of Grafana from sqlite3 to MySQL, a new schema is needed.
=> [OWL-974] Add a schema for DB migration of Grafana

modules/hbs/cache/gitupdate.go, modules/hbs/cache/gitupdate_test.go
Fix the problems that git lastest commit hash depends on  gitlab RSS subscription.
The whole story: https://humorless.github.io/2017/03/15/get-latest-commit-hash-from-git-repo/
=> [OWL-1563][hbs] modify how HBS get the lastest commit hash from git repo

common/db/nqm/agent.go, common/db/nqm/agent_test.go, common/db/nqm/testing/db.go, common/model/nqm/agent.go, common/model/nqm/query.go, modules/nqm-mng/cfg.example.json, modules/nqm-mng/main.go, modules/nqm-mng/restful/agent.go, modules/nqm-mng/restful/agent_it_test.go, modules/nqm-mng/restful/package.go
In this PR, two APIs are implemented. One is for getting the cached target list, the other is for clearing the cache. These two APIs, which are given the agent ID by the URLs, are for a specific agent.
=> [OWL-1333][OWL-1583] APIs for the cached target list

modules/agent/plugins/scheduler.go
原本的這段程式碼
https://github.com/Cepave/open-falcon-backend/commit/4244fa6f56f4d6d0c9193c8913a0c1d6917548e3
這是為了防呆，希望可以做欄位補齊。
後來發現這樣子改之後，plugin script 裡的 endpoint 欄位會備受限制，無法使用非 hostname 的值。所以做這次的修正。
=> [OWL-1662][agent] let agent to allow different endpoint in plugin script

modules/f2e-api/app/controller/graph/owl_graph_controller.go
change endpoint_id temp store variable's type to int64, cause we saved big number on graph database
=> change endpoint_id temp store variable's type to int64

modules/f2e-api/app/controller/dashboard_graph/dashboard_graph_controller.go, modules/f2e-api/app/controller/dashboard_graph/dashboard_graph_owl_controller.go, modules/f2e-api/app/controller/dashboard_graph/dashboard_structs.go, modules/f2e-api/app/controller/dashboard_screen/dashboard_screen_controller.go, modules/f2e-api/app/model/dashboard/dashboard_graph.go, modules/f2e-api/app/model/dashboard/dashboard_screen.go, modules/f2e-api/test/controller_test/dashboard_graph/create_method/dashboard_screen_create.go, modules/f2e-api/test/controller_test/dashboard_graph/dashboard_graph_test.go, modules/f2e-api/test/controller_test/dashboard_graph/struct/struct_test.go, scripts/mysql/db_schema/dashboard-db-schema.sql, scripts/mysql/dbpatch/change-log/change-log-dashboard.yaml, scripts/mysql/dbpatch/change-log/schema-dashboard/masato-3.sql
*  support set new name of copy api in dashboard_screen_clone/dashboard
*  modified db schema & model of dashboard graph
* add fields `time_range`, `y_scale`, `sort_by`, `sample_method` in dashboard_graph table
* unique name issue of dashboard_screen
* update response data format from owl-light f2e team
* support query screen list with creator name
=> [OWL-1766] Based on design of New graph/screen page changes f2e-api's api

modules/agent/g/const.go, modules/agent/plugins/update.go
Agent 6.0.0 上線之後，發現自動更新的功能有的時候會卡住。卡住的原因是 git fetch 和 git ls-remote 沒有考慮 timeout 的問題。這一版的 Agent 對上述的 git 指令加上 timeout 的限制。
=> [OWL-1828] fix Agent auto updating feature

modules/query/http/cron.go
boss database 內的 hosts table 資料在同步時，會依賴 grafana 資料庫的 idc table，造成有時候新的機房(IDC) 資訊不同步。
其實 boss database 裡有 idcs table 。所以更改依賴的 table 即可。改成 hosts table 的資料去依賴 boss database 的 idcs table 。而且 idcs table 本來就會週期性地做更新。
=> [OWL-1853] change the dependency of table boss.hosts from table grafana.idc to table boss.idcs

modules/mysqlapi/model/diag.go, modules/mysqlapi/rdb/diag.go, modules/mysqlapi/restful/diag.go, modules/mysqlapi/restful/diag_it_test.go, modules/mysqlapi/restful/package.go
New field `nqm.heartbeat.count` in the responsed JSON data is added.
In this PR, the code is moved from `common/` to `modules/rdb/mysqlapi/`.
This commit also rewrites the struct for marshaling JSON data and uses
the `mvc` handler by the way.
=> [OWL-1867][common][mysqlapi] `nqm.heartbeat.count`

modules/hbs/rpc/agent_stress_test.go
A stress test that simulates agents to send heartbeat requests simultaneously.
Modify `numberOfFakeAgents` to enable the test.
=> [OWL-1621] Stress test of heartbeat requests

scripts/mysql/dbpatch/change-log/schema-portal/masato-10.sql, scripts/mysql/dbpatch/change-log/schema-portal/masato-12.sql, scripts/mysql/dbpatch/change-log/schema-portal/masato-5.sql, scripts/mysql/dbpatch/change-log/schema-portal/masato-9.sql
fix issue of 「Patch 的內容不可附上資料庫的名稱」
`${trace}/trac/wiki/Owl/DevSpec/DbPatch`
=> fix issue of 「Patch 的內容不可附上資料庫的名稱」

modules/f2e-api/app/model/boss/boss_model.go
原本的 ORM mapping 關系是讓  BossHost 的 platform 對應到 hosts table 的 platform 欄位。
這個修改，改成讓 BostHost 的 platform 對應到 hosts table 的 platforms 欄位。如此就可以暫時解決掉平台復用的問題。
=> [OWL-1964] change platform ORM mapping to platforms
