Cepave/open-falcon-backend

- Makefile
- README.md
Now it runs `go fmt` for all files except the ones under `vendor/`.
> [OWL-370] Fix the bug of `format`

- commands/reload/reload.go
- commands/restart/restart.go
- commands/start/start.go
- commands/status/status.go
- commands/stop/stop.go
- commands/tail/tail.go
- main.go
Because we modified the name of the repository, the imported paths should be modified too.
> [OWL-384] `open-falcon` -> `open-falcon-backend`

- modules/query/http/alert.go
Add platform info for deactivated hosts, and mark them as "(deactivated)" in IP field.
> [OWL-818][query] add platform info for deactivated hosts

- modules/query/http/alert.go
> [OWL-826][query] integrate alarm API

- modules/fe/Portal_APIDoc.md
- modules/fe/http/portal/portal_controller.go
- modules/fe/http/portal/portal_routes.go
- modules/fe/model/falcon_portal/event_query_action.go
- modules/fe/test/portal_test/common.go
- modules/fe/test/portal_test/protal_event_case_test.go
- modules/fe/test/portal_test/protal_events_test.go
- modules/fe/test/portal_test/protal_note_test.go
also did:
1. fixed time range query isssue.
2. add more flexible query condition of query.
3. refactor code of portal api , make it more easy to mantain and understanding.  
4. add test code for full api converaged testing. (fake mysql & fake data required).
> [OWL-767][fe] filter ignored type as default of GetNotes api

- modules/query/http/api.go
- modules/query/http/zabbix.go
modified:   modules/query/http/zabbix.go
> [OWL-721][query] fix http panic: interface {} is nil

- modules/query/cfg.example.json
- modules/query/g/cfg.go
- modules/query/http/grafana.go
modified:   modules/query/http/grafana.go
> [OWL-743][query] add local query config in cfg.json

- modules/query/http/api.go
> [OWL-667][query] include deactivated hosts in filtered result

- modules/query/http/api.go
> [OWL-527][query] add API to return bandwidth upper limit of an IDC

- config/transfer.json
- modules/transfer/cfg.example.json
- modules/transfer/g/cfg.go
- modules/transfer/proc/proc.go
- modules/transfer/receiver/rpc/rpc_transfer.go
- modules/transfer/sender/conn_pool/staging_conn_pool_manager.go
- modules/transfer/sender/conn_pools.go
- modules/transfer/sender/send_queues.go
- modules/transfer/sender/send_tasks.go
- modules/transfer/sender/sender.go
Forward the data from the endpoint in filter list to Staging.
The filtering policy depends on same prefix.
> [OWL-279][transfer] Add Staging forwarding mechanism.

- modules/query/http/alert.go
- modules/query/http/api.go
> [OWL-845][query] exclude virtual IPs from hosts query responses

- modules/query/http/alert.go
> [OWL-826][query] fix missing contact for alert API

- modules/query/http/api.go
> [OWL-846][query] add API /api/hosts to return hosts data

- modules/query/http/api.go
> [OWL-854][query] add exception handling for http panic

- modules/fe/Dashboard_APIDoc.md
Add API documents the following API:
```
/api/v1/dashboard/endpointplugins
/api/v1/dashboard/endpointrunningplugins
/api/v1/dashboard/latestplugin
/api/v1/dashboard/counterendpoints
```
> [OWL-627][fe] add API document

- modules/agent/http/plugin.go
- modules/agent/http/plugin_test.go
**plugin/update API** will remove the plugin directory and re-clone again when it encounters **git pull error**
> [OWL-693][agent] change the behavior the plugin/update API

- modules/query/http/api.go
> [OWL-854][query] add exception handling for invalid memory address

- modules/fe/model/boss/paltfromApi.go
modified:   model/boss/paltfromApi.go
> [OWL-959][fe] fix IP and hostname mismatched bug

- common/model/expression.go
- modules/agent/cfg.example.json
- modules/fe/cfg.example.json
- modules/fe/g/cfg.go
- modules/fe/http/dashboard/dashboard_controller.go
- modules/fe/model/dashboard/endpoint.go
- modules/hbs/cache/cache.go
- modules/hbs/cache/gitupdate.go
- modules/hbs/cfg.example.json
- modules/hbs/db/config.go
- modules/hbs/db/expression.go
- modules/hbs/g/cfg.go
- modules/hbs/rpc/agent.go
Agent removes git addr from Agent's config.
HBS reads git addr from Mysql every minute.
Fe read git addr fro Mysql when it needs.
> [OWL-480][agent][fe][hbs][mysql] update plugin policy: move git repo addr from cfg.json to MySQL

- modules/nqm-agent/query.go
- modules/nqm-agent/rpc.go
In this PR, it prints the time duration between the last response from `hbs` and now if the duration is more than 6 minutes.
> [OWL-687][nqm-agent] Last response from `hbs`

- modules/query/conf/lambdaSetup.json
- modules/query/gin_http/computeFunc/computeFuncController.go
- modules/query/gin_http/computeFunc/computeFuncHelper.go
- modules/query/gin_http/grafana/grafanaController.go
- modules/query/gin_http/openFalcon/openFalconController.go
- modules/query/gin_http/web.go
- modules/query/js/avgCompare.js
- modules/query/js/sumAll.js
- modules/query/model/endpoint.go
1. removed dependence with dashboard module of open-falcon
2. support custom lambda query for  fastweb-openfalcon-datasource of  grafana front-end.
> [OWL-491] [query] Lambda query integrate with grafana 3.0

- modules/agent/cron/plugin.go
- modules/agent/cron/reporter.go
- modules/agent/g/tool.go
- modules/agent/g/transfer.go
- modules/hbs/cache/gitupdate.go
1  Fix OWL-935 using the PR of https://github.com/open-falcon/agent/pull/46/files
2  Fix OWL-867 , change the git repo update content inside policy between HBS <-> Agent
> [agent][hbs] fix the panic and update the plugin policy communicating with HBS

- modules/fe/Dashboard_APIDoc.md
- modules/fe/http/dashboard/dashboard_controller.go
- modules/fe/http/dashboard/dashboard_routes.go
- modules/fe/model/dashboard/endpoint.go
- modules/fe/model/dashboard/endpoint_counter.go
API `counters` can lookup **counters array** from **regular expression of counter**.  
API `counterendpoints` can lookup **endpoints array** from **counters array**
> [OWL-980][fe] provide 2 APIs to look up endpoints by counters with document of API

- modules/query/http/api.go
> [OWL-770] add bond mode and transmission limit info

- Makefile
- README.md
- config/agent.json
- config/confgen.sh
- config/fe.json
- config/graph.json
- config/hbs.json
- config/query.json
- config/transfer.json
- docker/common.yml
- docker/init.yml
- docker/mysql.cnf
It would be easier to test on your local machine starting from this PR:
1. MySQL and Redis are running in docker container.
2. Other backend modules are running in Go binaries.
3. The templating variables in cfg.json is applied when `make pack`.
> Using templating variables for environment setting.

- modules/query/http/api.go
> [OWL-770] update net.transmission.limit

- modules/alarm/cron/builder.go
- modules/alarm/cron/callback.go
- modules/alarm/cron/consumer.go
- modules/alarm/cron/reader.go
- modules/alarm/g/eventdto.go
- modules/alarm/model/event/event_operation.go
- modules/fe/model/falcon_portal/event_edit_action.go
1. beego orm's api is changed, Time type column is not support auto conversion now.
* fixed this issue of fe / alarm
2. change all import path from old cepave/common repo to cepave/open-falcon-backend/common
> [OWL-960] [alarm] [fe] fix issue of insert case_event to db that will got panic exception

- modules/fe/http/uic/auth_controller.go
modified:   modules/fe/http/uic/auth_controller.go
> [OWL-1063][fe] redirect to callback URL after third-party login

- scripts/mysql/db_schema/2-portal-db-schema.sql
- scripts/mysql/dbpatch/change-log/change-log-portal.yaml
- scripts/mysql/dbpatch/change-log/schema-portal/laurence-20.sql
- scripts/mysql/dbpatch/go/dbpatch.go
- scripts/mysql/dbpatch/go/dbpatch_test.go
1. add primary key to `falcon_portal.common_config`
2. fix db-patch source file's import path & gofmt db-patch source file
3. `git rm` exe file `db-patch`
> [OWL-1046] add primary key to falcon_portal.common_config & fix db-patch source import path

- config/query.json
- modules/query/cfg.example.json
- modules/query/g/cfg.go
- modules/query/http/alert.go
- modules/query/http/api.go
- modules/query/http/cron.go
- modules/query/http/http.go
- scripts/mysql/db_schema/boss-db-schema.sql
added:      modules/query/http/cron.go
added:      scripts/mysql/db_schema/boss-db-schema.sql
modified:   config/query.json
modified:   modules/query/http/http.go
> [OWL-1034][config][query][scripts] sync hosts and contacts data

- scripts/README.md
> [OWL-1067][scripts] add README.md for patch

- config/query.json
- modules/query/cfg.example.json
- modules/query/g/cfg.go
- modules/query/http/api.go
- modules/query/http/cron.go
- modules/query/http/http.go
modified:   config/query.json
modified:   modules/query/http/http.go
> [OWL-1034][config][query] add bossdb config and fix func syncContactsTable()

- modules/query/http/api.go
- modules/query/http/http.go
modified:   modules/query/http/http.go
> [OWL-1061] fix func getBandwidthsSum()

- modules/query/http/cron.go
> [OWL-1034][query] fix updated time check

- modules/query/http/cron.go
- modules/query/http/grafana_graph_options.go
modified:   modules/query/http/grafana_graph_options.go
> [OWL-1034][query] initialize idc table if it is empty

- modules/query/http/api.go
> [OWL-986][query] fix recent metric values missing problem

- modules/query/http/api.go
> [OWL-1029][query] add API for querying nic.out.speed metric

- cmd/check.go
- cmd/restart.go
- cmd/start.go
- cmd/stop.go
- g/tool.go
- g/tool_test.go
The function `rmDup()` is added at the beginnings of the commands.
> [OWL-1001][backend] Eliminate duplicated arguments

- config/fe.json
> #1 add boss database config for fe module

- modules/query/http/api.go
> [OWL-1105][query] improve performance of API /api/apollo/filters

- Makefile
- cmd/check.go
- cmd/restart.go
- cmd/start.go
- cmd/stop.go
- configure
- g/g.go
- g/tool.go
In this commit, these commands `start`, `stop`, `restart` and `check` handle the case of all module when no arguments are provided.
> [OWL-999][backend] Command all modules

- modules/query/http/api.go
> [OWL-1107][query] improve performance of API /api/alive/platforms

- modules/fe/Portal_APIDoc.md
- modules/fe/http/portal/onTimeUpdate_controller.go
- modules/fe/http/portal/portal_controller.go
- modules/fe/model/falcon_portal/alerts.go
- modules/fe/model/falcon_portal/event_query_action.go
- modules/query/model/endpoint.go
* make priority query support multiple value filtering.
* add boss filtering for on-time new event checking api.
* remove database init of endpoint model on query, this will make db connection reach limitation.
> [OWL-1108][fe] complete back-end filter api of evnetcase

- modules/query/http/api.go
> [OWL-1109][query] fix typo. replace warm with warn

- Makefile
- config/aggregator.json
- config/alarm.json
- config/confgen.sh
- config/judge.json
- config/nodata.json
- config/query.json
- config/sender.json
- config/task.json
- config/transfer.json
- modules/nqm-agent/query.go
- modules/nqm-agent/rpc.go
- modules/nqm-agent/task_test.go
- modules/nqm-agent/version.go
- modules/transfer/sender/sender.go
- modules/transfer/sender/sender_test.go
In this PR, I made the configuration files in `config/` use the variables defined in `config/confgen.sh`. However, there are some services that I can't figure out what they are currently. I either use `0.0.0.0` or `127.0.0.1` for them.
> [OWL-1125][backend] Generate configuration files by scripts

- modules/query/http/network_quality.go
> [OWL-1119][query] add API /api/nqm/jaguar

- modules/query/http/api.go
> [OWL-1087][query] add recent 10 min data in func getBandwidthsSum()

- modules/query/http/api.go
> [OWL-1201][query] add nic.default.out.speed

- modules/query/http/api.go
> [OWL-987][query] set condition for adding recent data

- modules/query/http/api.go
- modules/query/http/cron.go
- modules/query/http/http.go
modified:   modules/query/http/http.go
> [OWL-1165][query] sync contacts table

- modules/query/http/api.go
- modules/query/http/cron.go
> [OWL-1199][query] sync boss.ips table

- modules/query/http/api.go
> [OWL-1096][query] refine func getApolloFilters()

- scripts/mysql/db_schema/boss-db-schema.sql
- scripts/mysql/dbpatch/change-log/build_dbpatch.sh
- scripts/mysql/dbpatch/change-log/change-log-boss.yaml
- scripts/mysql/dbpatch/change-log/patch_boss.sh
- scripts/mysql/dbpatch/change-log/schema-boss/laurence-2.sql
modified:   scripts/mysql/db_schema/boss-db-schema.sql
> [OWL-1205][scripts] add boss.idcs, boss.ips, and boss.nodes tables

- modules/nqm-agent/main.go
- modules/nqm-agent/marshal_test.go
- modules/nqm-agent/query.go
- modules/nqm-agent/task_test.go
In this PR, `nqm-agent` reloads `cfg.json` when `cfg.json` is changed.
> [OWL-689][nqm-agent] Reload `cfg.json` when the file is changed

- modules/query/http/cron.go
> [OWL-1199][query] set ip.Exist = 1

- modules/query/http/cron.go
> [OWL-1085][query] refine condition for setting exist = 0 in boss.ips table"

- modules/query/http/cron.go
> replace CONVERT_TZ(NOW(),'+00:00','+08:00') with CONVERT_TZ(NOW(),@@session.time_zone,'+08:00')

- modules/query/http/api.go
> [OWL-1089][query] remove ip and hostname tags to reduce API response time

- modules/query/http/api.go
> [OWL-1221][query] merge IPs of a host within a platform

- modules/query/http/api.go
> [OWL-1226][query] fix func appendUniqueString()

- modules/query/http/api.go
- modules/query/http/cron.go
> [OWL-1223][query] add API /api/hostgroups

- modules/query/http/cron.go
> [OWL-1199][query] fix func updateIPsTable()

- modules/query/http/network_quality.go
> [OWL-1236] fix API /api/nqm/jaguar

- modules/query/http/network_quality.go
> [OWL-1236][query] fix NQM time selector

- modules/query/http/api.go
> [OWL-1089][query] reduce content of response of API /api/apollo/filters

- common/logruslog/logruslog.go
I added a customized hook in the logger of `logrus`.
> [OWL-1246][common] Print stack message in log

- modules/nqm-agent/cfg.go
In this commit, I use `net.ParseIP()` to validate the values of IP addresses from `cfg.json` and the output of `dig` command.
> [OWL-1250][nqm-agent] Validation of metadata's IP

- modules/query/http/network_quality.go
> [OWL-1236][query] replace setError() with log.Debugf()

- modules/query/http/api.go
> [OWL-987][query] refine func convertDurationToPoint()

- modules/nqm-agent/version.go
> [nqm-agent] v0.10.0

- modules/query/http/api.go
> [OWL-1232][query] assign a host to a platform only if it's real IP is assigned to the platform

- modules/agent/http/http.go
- modules/agent/http/tail.go
```curl 10.20.30.40:1988/v1/tail -XGET -d '{"MaxLineNumber":20}'```
> [OWL-1267][agent] Add http tail API to read agent log

- modules/agent/g/const.go
- modules/agent/http/tail.go
> [OWL-1267][agent] add white ip list protection

- modules/fe/cfg.example.json
- modules/fe/g/cfg.go
- modules/fe/http/uic/auth_controller.go
modified:   modules/fe/cfg.example.json
modified:   modules/fe/g/cfg.go
modified:   modules/fe/http/uic/auth_controller.go
> [OWL-1164][fe] add single sign-on

- modules/transfer/sender/send_tasks.go
Fixed the bug in which `tcpping` and `tcpconn` use the `SendToNqmIcmpCnt` and `SendToNqmIcmpFailCnt`.
> [OWL-1258][transfer] Fix the wrong counters.

- modules/query/http/cron.go
> [OWL-1239][query] mute or unmute alarms by cron every one minute

- modules/query/http/api.go
本來的邏輯有兩種錯誤。這次主要修正了下列的兩點： 
1. make the `plugin` field will not have dirty value.
2. make the `version` and `plugin` fields will have values even when `status`  field is `deactivated`.
> [OWL-1340][query] fix api/alive/platforms

- modules/query/http/network_quality.go
> [OWL-1310][query] add API for NQM nodes history page

- modules/query/http/api.go
> [OWL-1315][query] add condition for 'customized' metric type

- modules/query/http/network_quality.go
> [OWL-1309][query] add API for NQM nodes ping details page

- modules/query/http/api.go
> [OWL-1358][query] fix func getBandwidthsSum()

- modules/fe/cfg.example.json
- modules/fe/g/cfg.go
- modules/fe/http/portal/onTimeUpdate_controller.go
- modules/fe/http/portal/portal_controller.go
> [OWL-1368] [fe] Set boss filter as configure option.

- modules/query/http/api.go
> [OWL-1146][query] refine func convertDurationToPoint()

- modules/query/model/nqm/compound_report.go
- modules/query/model/nqm/compound_report_test.go
>  [OWL-1441] NQM 綜合查詢 API，100% 掉包時，min/max 等值的排序

- modules/query/http/api.go
> [OWL-793][query] add disks and io metric types

- modules/query/http/api.go
> [OWL-1475][query] add API for platform bandwidth breakdown by ISP

- scripts/mysql/db_schema/boss-db-schema.sql
- scripts/mysql/dbpatch/change-log/change-log-boss.yaml
- scripts/mysql/dbpatch/change-log/schema-boss/laurence-4.sql
DB patch modify 4 tables. 
DB patch commands generated by mysqldiff
> [OWL-1527][scripts] modify 4 tables in boss databases to conform new boss operations.

- modules/query/cfg.example.json
- modules/query/g/cfg.go
- modules/query/graph/graph.go
- modules/query/http/api.go
- modules/query/http/cron.go
modified:   modules/query/graph/graph.go
modified:   scripts/mysql/db_schema/boss-db-schema.sql
> [OWL-1527][query] sync platform type and IP type

- modules/query/cfg.example.json
- modules/query/g/cfg.go
- modules/query/http/api.go
- modules/query/http/cron.go
- modules/query/http/network_quality.go
> [OWL-1527][query] use configurable time to trigger func SyncHostsAndContactsTable()

- modules/fe/Dashboard_APIDoc.md
- modules/fe/http/dashboard/dashboard_controller.go
- modules/fe/http/dashboard/dashboard_routes.go
本來 lastetplugin 計算的方式，依賴於 gitlab 的 RSS 訂閱。    
現在改成使用 git ls-remote 的方式來取得最新的 commit hash
> [OWL-1566][fe] fix API api/v1/dashboard/latestplugin

- common/gin/config.go
- modules/api/app/controller/graph/owl_graph_controller.go
- modules/api/app/controller/routes.go
- modules/api/app/helper/filter/boss_filter.go
- modules/api/app/helper/filter/hg_filter.go
- modules/api/config/database.go
- modules/api/owl_new_graph.md
- trash.yml
1. add health check api for api module
2. during ci, I found a common package was updated that will broken ours current module (ex. api , nqm-query). so I add trash mechanism to fix this issue.
> [OWL-1572][OWL-1551][common][api] add health check for api module

- common/db/owl/location.go
- common/db/owl/location_test.go
- modules/nqm-mng/restful/isp.go
- modules/nqm-mng/restful/location.go
- modules/nqm-mng/restful/package.go
Now it supports getting ISP/province/city by ID.
> [OWL-1231][common][nqm-mng] Get a location by ID

- modules/transfer/main.go
- modules/transfer/sender/conn_pool/influxdb_conn_pool_manager.go
- modules/transfer/test/rpcclient.py
changed open-falcon tags stored schema. more info please refer: OWL-1570
> [OWL-1588] [transfer] Reformat schema influxdb

- .gitignore
- modules/query/http/cron.go
> [OWL-1527][query] add exception handling in func getPlatformsType()

- modules/query/http/api.go
> [OWL-1544][query] add func getGraphLastData()

- modules/query/cfg.example.json
- modules/query/g/cfg.go
- modules/query/http/api.go
- modules/query/http/cron.go
- modules/query/http/http.go
- scripts/mysql/db_schema/apollo-db-schema.sql
modified:   modules/query/graph/graph.go
> [OWL-1518][query] store platform bandwidth data in net table

- modules/query/http/api.go
> [OWL-1202][query] add API /api/apollo/remarks/add

- modules/query/http/api.go
> [OWL-1202][query] fix func getBandwidthsSum()

- modules/query/http/api.go
> [OWL-1202][query] fix func getPlatformBandwidthsByISP()

- modules/query/http/api.go
- modules/query/http/cron.go
> [OWL-1202][query] add o.Using(apollo)

- modules/nqm-mng/model/heartbeat.go
- modules/nqm-mng/rdb/heartbeat.go
- modules/nqm-mng/rdb/heartbeat_test.go
- modules/nqm-mng/rdb/package_test.go
- modules/nqm-mng/restful/heartbeat.go
- modules/nqm-mng/restful/heartbeat_it_test.go
- modules/nqm-mng/restful/package.go
Implement API layer, processing layer, and testing.
> [OWL-1645][nqm-mng] Implement /agent/heartbeat API

- .dockerignore
- .gitlab-ci.yml
- docker/alpine/17847.patch
- docker/alpine/Dockerfile
- docker/alpine/go-wrapper
- docker/alpine/no-pic.patch
- docker/alpine/run.sh
- docker/docker-healthcheck
Clean building folder & go toolchain to reduce the image size.
> [IN-106] Dockerfile for image building.

- modules/f2e-api/app/controller/host/hostgroup_controller.go
- modules/f2e-api/app/controller/template/template_controller.go
- modules/f2e-api/app/controller/template/template_routes.go
- modules/f2e-api/app/model/falcon_portal/grp_tpl.go
add copy template api on fe2-api module
`/api/v1/template/clone_tpl`
> [OWL-1675][f2e-api] Add copy templeate api

- modules/agent/g/const.go
因為要布署新版的 Agent ，所以要打上新的 Agent 版號。
> [OWL-1644-a] add new agent version number

- modules/agent/http/plugin.go
- modules/agent/plugins/scheduler.go
- modules/agent/session/session.go
- modules/agent/session/session_test.go
` sys.CmdRunWithTimeout` 這個來自 toolkit 的函數最新版本的有問題。
所以改成 `session.CmdSessionRunWithTimeout`
> [OWL-1644] fix error from toolkits --- CmdRunWithTimeout

- modules/f2e-api/app/controller/alarm/alarm_notes_controller.go
missing timestamp for add note api
> [OWL-1673] [f2e-api] add missing timestamp for add note api

- modules/query/http/cron.go
- modules/query/http/cron_test.go
重構了 query 的 ```updateHostsTable``` , 改成用比較有效率的方式來執行 SQL
> [OWL-1206] 重構了 query 的 updateHostsTable

- modules/f2e-api/app/controller/dashboard_graph/dashboard_graph_controller.go
- modules/f2e-api/app/controller/dashboard_graph/dashboard_graph_routes.go
- modules/f2e-api/app/controller/dashboard_screen/dashboard_screen_controller.go
- modules/f2e-api/app/controller/dashboard_screen/dashboard_screen_routes.go
- modules/f2e-api/test/api_token_test.go
- modules/f2e-api/test/cfg_test.json
- modules/f2e-api/test/controller_test/dashboard_graph/dashboard_graph_test.go
- modules/f2e-api/test/controller_test/dashboard_screen/dashboard_screen_test.go
* add dashboard_screen clone api
* add test script for test dashboard_screen clone api
* fix delete action of dashboard_screen
* add graph clone api
* fix graph update api
* method can not set to empty
* falcon_tags can not set to empty
* add test script for test clone graph & update graph
> [OWL-1805][f2e-api] add screen clone & graph clone apis

- config/f2e-api.json
- modules/f2e-api/app/controller/uic/session_controller.go
- modules/f2e-api/app/controller/uic/third_party_controller.go
- modules/f2e-api/app/controller/uic/user_controller.go
- modules/f2e-api/app/controller/uic/user_routes.go
- modules/f2e-api/app/model/uic/session.go
- modules/f2e-api/app/model/uic/user.go
- modules/f2e-api/cfg.json.example
* also removed skip_auth, because we already support integrate api with tokens.
> [OWL-1815] support Third party api login with BOSS api v2

- common/model/graph.go
- modules/f2e-api/app/controller/expression/expression_controller.go
- modules/f2e-api/app/controller/graph/grafana_controller.go
- modules/f2e-api/app/controller/graph/graph_controller.go
- modules/f2e-api/app/controller/graph/graph_routes.go
- modules/f2e-api/app/controller/host/hostgroup_controller.go
- modules/f2e-api/app/controller/uic/team_controller.go
- modules/f2e-api/app/controller/uic/user_controller.go
- modules/f2e-api/app/controller/uic/user_routes.go
- modules/f2e-api/app/helper/session.go
- modules/f2e-api/app/model/graph/endpoint_counter.go
- modules/f2e-api/app/model/graph/tag_endpoint.go
- modules/f2e-api/app/utils/to_string.go
* add grafana api
* add api GetTeamByName from falcon-plus
* update model for graph
* merge bug fix of falcon-plus on hostgroup_controller.go 
* merge bug fixing of falcon-plus on expression_controller.go
* make admin can create user account when sign up is disable
> [OWL-1826] merge update [20170607] from falcon_plus/module/api

- modules/alarm/model/event/event.go
- modules/f2e-api/app/controller/alarm/alarm_extends_controller.go
1. use md5 to encode base64sha
2. remove one line error message checking, sometimes this may cause of nullpoint exception
> [OWL-1859] fix 2 issue

- config/f2e-api.json
> fix: (f2e-api) update default password

- config/query.json
- modules/query/http/http.go
> chore(query) fix missing db config.

- LICENSE
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>
> add Apache License

- common/model/graph.go
- modules/graph/api/graph.go
1. fixed error show on starting graph module.
2. create general model for rpc communication usage
> [OWL-1843] fix pointer error of rpc issue

- config/fe.json
- modules/fe/cfg.example.json
- modules/fe/model/falcon_portal/alerts.go
- modules/fe/model/falcon_portal/event_query_action.go
fix time filter of get alarms
set default will filter all actived = 0 alarm_events
> [OWL-1849] fix 2 issue

- common/testing/jsonrpc/ginkgo.go
- modules/hbs/rpc/agent_stress_test.go
- modules/hbs/rpc/package.go
- modules/hbs/service/agent_heartbeat.go
- modules/hbs/service/agent_heartbeat_test.go
- modules/hbs/service/mysql_api.go
- modules/hbs/service/package.go
- modules/hbs/service/package_test.go
Including:
- Panic when empty host or illegal URL
- Fix bug in the stress test.
- Better error message format.
- Unit tests for URL resolving.
> [OWL-1621] Improve error handling of agent heartbeat service

- config/f2e-api.json
- modules/f2e-api/app/controller/graph/grafana_controller.go
- modules/f2e-api/app/controller/graph/graph_controller.go
- modules/f2e-api/app/controller/graph/owl_graph_controller.go
- modules/f2e-api/app/controller/host/hostgroup_controller.go
- modules/f2e-api/app/controller/strategy/strategy_controller.go
- modules/f2e-api/app/controller/template/template_controller.go
- modules/f2e-api/app/controller/uic/team_controller.go
- modules/f2e-api/app/controller/uic/user_controller.go
- modules/f2e-api/app/helper/filter/hg_filter.go
- modules/f2e-api/app/helper/filter/host_filter.go
- modules/f2e-api/app/model/falcon_portal/host.go
- modules/f2e-api/cfg.json.example
- modules/f2e-api/config/database.go
- modules/f2e-api/main.go
1. grafana query issue
2. response result improvement
> [OWL-1896] improve & bug fixing of some api

- modules/f2e-api/app/controller/template/template_controller.go
- modules/f2e-api/app/controller/uic/team_controller.go
1. add some options, to improve api response size. (when client only need a simple list not full) 
2. change some api params binding way of template & team controller 
3. fix pagging broken
> [OWL-1907] improve api response size & fix pagging issue

- modules/f2e-api/app/helper/filter/boss_filter.go
在這個修改之前，在 UI 上的呈現會是多個平台：
c01.i05 (152)
c01.i05,fastbat (2)
c01.i05,fastbat,lvs (1)
改完之後，只會有 
c01.i05 (166)
> [OWL-1964] modify platforms to platform in UI

- modules/f2e-api/lambda_extends/ReadMe.md
本來的 Readme 的範例是錯的。我把錯的改正。並且補上一個 curl 的範例。
> fix bug in lambda_extends/ReadMe.md

- common/model/mysqlapi/diag.go
- common/model/mysqlapi/health_service.go
- common/service/mysql_api.go
- common/service/mysql_api_test.go
- modules/hbs/g/cfg.go
- modules/mysqlapi/rdb/diag.go
- modules/mysqlapi/restful/diag.go
Eliminate dependency of mysql-api module from common/model.
> [OWL-1866] Eliminate dependency from common model
